# zmodload zsh/zprof
# Check if zplug is installed
if [[ ! -d ~/.zplug ]]; then
  git clone https://github.com/zplug/zplug ~/.zplug
  source ~/.zplug/init.zsh && zplug update --self
fi

# Essential
source ~/.zplug/init.zsh

zplug "robbyrussell/oh-my-zsh", use:"lib/*.zsh"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-syntax-highlighting"

zplug "plugins/git", from:oh-my-zsh
zplug "plugins/history", from:oh-my-zsh
zplug "plugins/homebrew", from:oh-my-zsh
zplug "plugins/fasd", from:oh-my-zsh
zplug "plugins/python", from:oh-my-zsh
zplug "plugins/colored-man-pages", from:oh-my-zsh
zplug "plugins/colorize", from:oh-my-zsh
zplug "plugins/thefuck", from:oh-my-zsh
zplug "plugins/virtualenv", from:oh-my-zsh, lazy:on
zplug "plugins/virtualenvwrapper", from:oh-my-zsh
zplug "plugins/autoenv", from:oh-my-zsh

zplug "themes/robbyrussell", from:oh-my-zsh


# Install packages that have not been installed yet
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi

zplug load


### Load dotzsh
# source "$DOTZSH/init.zsh"

### Customize to your needs...

# Base case is standard python




if [[ "$OSTYPE" == "linux-gnu" ]]; then
        # ...
        alias edit="vim"
elif [[ "$OSTYPE" == "darwin"* ]]; then
        # Mac OSX

        # Make it so you can toggle what's shown in finder
        alias showfiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.app'
        alias hidefiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'

        alias edit="subl -n"
        alias finder="open ."
        export EDITOR='subl -w'
        export VIRTUALENVWRAPPER_PYTHON=`which python3`
        alias updatedb="sudo /usr/libexec/locate.updatedb"
        alias pip=pip3

elif [[ "$OSTYPE" == "cygwin" ]]; then
        # POSIX compatibility layer and Linux environment emulation for Windows
elif [[ "$OSTYPE" == "msys" ]]; then
        # Lightweight shell and GNU utilities compiled for Windows (part of MinGW)
elif [[ "$OSTYPE" == "win32" ]]; then
        # I'm not sure this can happen.
elif [[ "$OSTYPE" == "freebsd"* ]]; then
        # ...
else
        # Unknown.
fi



if [[ -n $(command -v hub) ]]; then
  alias git=hub
fi

source $HOME/.zshfunctions

alias edit_rc="edit $HOME/.dotfiles/zsh/zshrc"
alias edit_ssh="edit $HOME/.ssh/config"
alias dotsync="$HOME/.dotfiles/dotsync/bin/dotsync"
unsetopt auto_cd


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
# zprof